"""Increase password_hash length to 254

Revision ID: 50a6305ae80b
Revises: 6a7000703a76
Create Date: 2025-07-25 18:28:48.995134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a6305ae80b'
down_revision: Union[str, Sequence[str], None] = '6a7000703a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=254),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_user', 'password_hash',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
